### ISSUE TITLE
Replacing GitHub organization logo

### ISSUE THREAD

**Issue by gronke** [iocage/iocage.github.io#2]
The logo if the GitHub Organisation has a grey bar on the right and also comes with white background.

The file should be replaced with this 500x500 pixel variant with transparent background:

![cmyk_iocage_lock_onlight_cropped_github](https://user-images.githubusercontent.com/473924/44627101-70241900-a928-11e8-805c-269da6e3dbd2.png)

**Comment by skarekrow** [comment]
:+1:
